services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    restart: on-failure
    env_file:
      - .env

    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD_FILE=${MYSQL_PASSWORD_FILE}
      - MYSQL_ROOT_PASSWORD_FILE=${MYSQL_ROOT_PASSWORD_FILE}
      - TZ=${TZ}
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=$$(cat ${MYSQL_ROOT_PASSWORD_FILE}) || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    secrets:
      - db_password
      - wp_admin_password
      - wp_user_password
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/${PHP_FPM_PORT}' || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 10s

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      wordpress:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html:ro
    networks:
      - inception

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_root_password:
    file: ./secrets/db_root_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt

volumes:
  db_data:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ${HOST_DB_PATH}
  wp_data:
    driver: local
    driver_opts:
      type: bind
      o: bind
      device: ${HOST_WP_PATH}

networks:
  inception:
    name: ${INCEPTION_NET}


#hello darkness my friend
